# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -rf.czu@yandex.ru
    on_success: never # default: change
    on_failure: always # defa,ult: always

env:
  global:
    - CODECOV_TOKEN="6ff6ade6-e01f-4d88-aa42-15337450ea90"

